language: ruby
sudo: required
addons:
  chrome: stable
rvm:
  - "2.6.5"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - export DISPLAY=:99.0
  - gem install bundler
  - bundle install
  - bundle exec gemsurance
services:
  - xvfb
  - mysql
  - redis-server
before_script:
  - mysql -u root -e "CREATE USER 'disease_trakker'@'localhost'; GRANT ALL PRIVILEGES ON *.* TO 'disease_trakker'@'localhost'; create database disease_trakker_test;"
  - yarn install --ignore-engines
script:
  - ./node_modules/.bin/eslint app/javascript/components/
  - bundle exec brakeman -qAzw1
  - bundle exec rake test
  - bundle exec rake test:system
  - yarn audit
  - rubocop
