version: "3"

services:
  sara-alert-enrollment:
    image: ${SARA_ALERT_IMAGE}:latest
  sara-alert-assessment:
    image: ${SARA_ALERT_IMAGE}:latest
  sidekiq-enrollment-mailer:
    image: ${SARA_ALERT_IMAGE}:latest
  sidekiq-enrollment-default:
    image: ${SARA_ALERT_IMAGE}:latest
  sidekiq-bridge-enrollment:
    image: ${SARA_ALERT_IMAGE}:latest
  sidekiq-bridge-assessment:
    image: ${SARA_ALERT_IMAGE}:latest

