test:
  service: Disk
  root: <%= Rails.root.join('tmp', 'test-storage') %>

development:
  service: Disk
  root: <%= Rails.root.join('tmp', 'storage') %>

amazon:
  service: S3
  access_key_id: <%= ENV.fetch("AWS_S3_ACCESS_KEY_ID") { '' } %>
  secret_access_key: <%= ENV.fetch("AWS_S3_SECRET_ACCESS_KEY") { '' } %>
  bucket: <%= ENV.fetch("AWS_S3_BUCKET") { '' } %>
  region: <%= ENV.fetch("AWS_S3_REGION") { '' } %>
  upload:
    server_side_encryption: AES256

minio:
  service: S3
  access_key_id: <%= ENV.fetch("MINIO_ACCESS_KEY") { '' } %>
  secret_access_key: <%= ENV.fetch("MINIO_SECRET_KEY") { '' } %>
  bucket: <%= ENV.fetch("MINIO_BUCKET") { '' } %>
  region: us-east-1
  endpoint: <%= ENV["MINIO_ENDPOINT"] %>
  force_path_style: true

# Examples of additional services below:

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
#   region: us-east-1
#   bucket: your_own_bucket

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
